disabledMods = [
  "minecraft",
  "armorandtools",
  "inmis",
  "lootr",
  "farm_and_charm",
  "lilis_lucky_lures",
  "herbalbrews",
  "alpinewhispers",
  "meadow",
  "candlelight",
  "beachparty",
  "bakery",
  "brewery",
  "vinery",
  "lilis_pottery",
  "tide",
  "stal-alloys",
  "endrem",
  "niftycarts",
  "adventurez",
  "natures_spirit",
  "environmentz",
  "earth-and-water",
  "another_furniture",
  "fleshz",
  "smallships",
  "storagedrawers",
  "betterarcheology",
  "heater",
  "earlystage"
]
