[logbegone]
phrases = [
    "Failed to remove item with identifier",
    "[Antique Atlas] Set fallback biome for",
    "[Antique Atlas] No fallback could be found for",
    "was corrected from null to its default",
    "has been sitting for 100 ticks, forgetting",
    "Hanging entity at invalid position:",
    "Received passengers for unknown entity",
    "Missing sound for event:",
    "Unable to play empty soundEvent:",
    "Empty height range: [-55 absolute--60 absolute]"
]
regex = []
