[logbegone]
phrases = [
    "Failed to remove item with identifier",
    "[Antique Atlas] Set fallback biome for",
    "[Antique Atlas] No fallback could be found for",
    "was corrected from null to its default",
    "has been sitting for 100 ticks, forgetting",
]
regex = []
